# sponsor this project: https://www.patreon.com/sebastianjn007
patreon: sebastianjnuwu
# sponsor this project: https://ko-fi.com/sebastianjn007
ko_fi: sebastianjnuwu
# sponsor this project: https://liberapay.com/sebastianjn007
liberapay: sebastianjnuwu