name: php-cs-fixer

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  npm install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: npm install
      uses: npm install

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply php-cs-fixer changes