name: 🚁 commit automatico

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        
   - uses: actions/setup-node@v1
        with:
          node-version: "16.7.0"
          
    - name: verificar status
      run: npm ci 
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update nos bancos de dados e configurações!
        