name: Monitor

on:
  workflow_dispatch:
  schedule:
    - cron:  "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12.18.3"
      
      - name: 🛸 Check status
        run: npm start 

      - name: ⌨️ Commit files
        run: |
          git config --local user.email "kettraworld@gmail.com"
          git config --local user.name  "Rehhbeka"
          git add .
          git commit -m "🗒️ Updated Summary"

      - name: 🚀 Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}