name: Scheduled Ping

# This workflow is triggered at a scheduled interval of every 30 minutes

on:

  schedule:

    # * is a special character in YAML so you have to quote this string.

    # /30 denotes that it will run once every 30 minutes

    - cron:  '*/2 * * * *'

jobs:

  pinger_job:

    name: A job to ping

    runs-on: ubuntu-latest

    env:

      URL: https://KellyWorld.kettraworld.repl.co

    steps:

      - id: ping

        uses: sisodiya2421/pinger@master
